# Generated by Django 5.2.7 on 2025-11-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_productcategory_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='catalog/product/', verbose_name='Image'),
        ),
    ]
