# Generated by Django 5.2.7 on 2025-11-22 21:09

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='catalog/categories', verbose_name='Image'),
        ),
    ]
