# Generated by Django 5.2.7 on 2025-12-19 11:08

import django.utils.timezone
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to='catalog/product/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
