# Generated by Django 5.2.7 on 2026-01-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
