# Generated by Django 5.2.7 on 2026-01-08 19:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_page_options_page_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=tinymce.models.HTMLField(blank=True, max_length=255, null=True, verbose_name='Content'),
        ),
    ]
