# Generated by Django 5.2.7 on 2026-01-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_category_options'),
        ('main', '0003_alter_page_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Sort')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activated')),
                ('products', models.ManyToManyField(to='catalog.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'product carousel',
                'verbose_name_plural': 'products carousel',
                'ordering': ['sort'],
            },
        ),
    ]
